###########################################################################
                          ###Admin User #####

///Admin Login/// 

POST http://localhost:4000/admin/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password" : "admin@123"
    
}

////////////////////////////////////////////////////
///Admin Create User////
#####

POST http://localhost:4000/admin/addUser
Content-Type: application/json;

{
    "billnumber":"123PRITAMAMAM",
    "email": "pritam@gmail.com",
    "phonenumber":"djbjsnmdnsmdnd",
    "startDate":"344.dc",
    "password":"pritam@123"
}


