####Super Admin ######
##Login##

POST http://localhost:4000/root/login
Content-Type: application/json

{
    "email":"admin@admin.com",
    "password":"admin@123"
}

####Get All Admins ####

GET http://localhost:4000/root/getAllAdmins
Content-Type: application/json

######Add Admin######
POST http://localhost:4000/root/addAdmin
Content-Type: application/json

{
"email":"admin@admin.com",
"password":"admin@123"
}

####Delete Admin ####
DELETE http://localhost:4000/root/deleteAdmin/62d71002e14c8b7f0ec7e411
Content-Type: application/json


###Logout #####
POST http://localhost:4000/root/logout
Content-Type: application/json
